export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        charcoal: 'var(--color-charcoal)',
        sage: {
          DEFAULT: 'var(--color-sage)',
          light: 'var(--color-light-sage)',
          dark: 'var(--color-dark-sage)',
        },
        cream: 'var(--color-cream)',
        'warm-white': 'var(--color-warm-white)',
        slate: 'var(--color-slate)',
        'deep-blue': 'var(--color-deep-blue)',
        brown: 'var(--color-brown)',
        'deep-red': 'var(--color-deep-red)',
        offwhite: 'var(--color-off-white)',
        gray: {
          light: 'var(--color-light-gray)',
          mid: 'var(--color-mid-gray)',
          dark: 'var(--color-dark-gray)',
        },
        tan: 'var(--color-tan)',
        sand: 'var(--color-sand)',
        bark: 'var(--color-bark)',
        forest: 'var(--color-forest)',
        bg: {
          primary: 'var(--bg-primary)',
          secondary: 'var(--bg-secondary)',
          elevated: 'var(--bg-elevated)',
          surface: 'var(--bg-surface)',
          inverse: 'var(--bg-inverse)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          inverse: 'var(--text-inverse)',
          accent: 'var(--text-accent)',
        },
      },
      fontFamily: {
        primary: 'var(--font-primary)',
        display: 'var(--font-display)',
      },
      spacing: {
        '2xs': 'var(--space-2xs)',
        xs: 'var(--space-xs)',
        sm: 'var(--space-sm)',
        md: 'var(--space-md)',
        lg: 'var(--space-lg)',
        xl: 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        '3xl': 'var(--space-3xl)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-default)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      fontSize: {
        display: ['36px', '1.1'],
        h1: ['28px', '1.2'],
        h2: ['22px', '1.25'],
        h3: ['16px', '1.3'],
        body: ['16px', '1.5'],
        small: ['14px', '1.5'],
        caption: ['12px', '1.4'],
        overline: ['11px', '1.2', { letterSpacing: '0.12em', textTransform: 'uppercase' }],
      },
    },
  },
  plugins: [],
}
